language: go
go:
  - 1.3
  - 1.4
  - tip
env:
  matrix:
    - BUILD_GOOS=linux BUILD_GOARCH=amd64
    - BUILD_GOOS=linux BUILD_GOARCH=arm
    - BUILD_GOOS=darwin BUILD_GOARCH=amd64
    - BUILD_GOOS=windows BUILD_GOARCH=amd64

script:
  - gvm cross $BUILD_GOOS $BUILD_GOARCH
  - GOARCH=$BUILD_GOARCH GOOS=$BUILD_GOOS go build
  - GOARCH=$BUILD_GOARCH GOOS=$BUILD_GOOS go test ./...
