sudo: false
language: go
go:
- 1.5.3
env:
- PATH=/home/travis/gopath/bin:$PATH
before_install:
- env
- npm --version
- go version
- git fetch --unshallow
- git describe --tags --dirty --long
- go get github.com/mitchellh/gox
- go get github.com/tcnksm/ghr
- go get github.com/axw/gocov/gocov
- go get github.com/mattn/goveralls
- go get golang.org/x/tools/cmd/cover
- nvm install 4.2
script:
- make && go test ./... && ./runcover.sh ./...
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && goveralls -coverprofile=profile.cov -service travis-ci -repotoken $COVERALLS_TOKEN'
after_success:
- gox -ldflags="-s -w -X main.version=${TRAVIS_TAG:-$TRAVIS_COMMIT}" -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}"
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then ghr --username boivie --token $GITHUB_TOKEN --replace --prerelease --debug -c $TRAVIS_COMMIT latest dist/; fi
- if [ "$TRAVIS_TAG" != "" ]; then ghr --username boivie --token $GITHUB_TOKEN --replace -c $TRAVIS_COMMIT $TRAVIS_TAG dist/; fi
notifications:
  email:
    recipients:
      - victor@boivie.com
    on_success: always
