sudo: false
language: go
go:
- 1.5.3
env:
- PATH=/home/travis/gopath/bin:$PATH
before_install:
- go get github.com/mitchellh/gox
- go get github.com/tcnksm/ghr
- go get github.com/axw/gocov/gocov
- go get github.com/mattn/goveralls
- go get golang.org/x/tools/cmd/cover
script:
- make && go test ./... && ./runcover.sh ./...
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && goveralls -coverprofile=profile.cov -service travis-ci -repotoken $COVERALLS_TOKEN'
after_success:
- gox -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}"
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && ghr --username boivie --token $GITHUB_TOKEN --replace --prerelease --debug pre-release dist/'
